# bitnet.cpp-env/docker-compose.yml
services:
  bitnet:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HF_REPO_ARG: ${HF_REPO:-HF1BitLLM/Llama3-8B-1.58-100B-tokens}  # デフォルトのモデル名
        QUANT_TYPE_ARG: ${QUANT_TYPE:-i2_s}                            # デフォルトの量子化タイプ
    container_name: bitnet_container
    volumes:
      - ./BitNet:/app/BitNet           # BitNet コードをマウント
      - ./models:/app/models           # モデルディレクトリをマウント
    environment:
      - HF_REPO=${HF_REPO:-HF1BitLLM/Llama3-8B-1.58-100B-tokens}
      - QUANT_TYPE=${QUANT_TYPE:-i2_s}
    tty: true                          # インタラクティブなセッションを可能に
