# bitnet.cpp-env/docker-compose.yml

services:
  bitnet:
    build: .
    container_name: bitnet
    volumes:
      - ./models:/app/BitNet/models
      - ./logs:/app/BitNet/logs
    stdin_open: true
    tty: true
